export enum Emojis {
  DUCK = '🦆',
  RADIOSTATION = '📻',
  NEWS = '📰',
  COUNTRY = '🌍',
  QUACK = '🦆🦆',
  SQUEAK = '🐤🐤',
  NOSOUND = '',
  ALERT = '🚨',
  MONEY = '💰',
  CAR = '🚗',
  SURPRISE = '😱',
  SUNNY = '☀️',
  HEHE = '😂',
  WOW = '😮',
  GOSSIPYNEIGHBOR = '🤷',
  WTF = '🤯',
}